// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsF54gj1MUn8Xw5lULj9QnPup3I7p8bIE',
    appId: '1:108494691697:web:2cbfcd8bdc78ea20b7aad0',
    messagingSenderId: '108494691697',
    projectId: 'test-app-103b4',
    authDomain: 'test-app-103b4.firebaseapp.com',
    storageBucket: 'test-app-103b4.firebasestorage.app',
    measurementId: 'G-DFJL2S1JTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAutpuufX7NP6suHhrz9NQsGBGh_FREeHk',
    appId: '1:108494691697:android:6a981f60897ba6cfb7aad0',
    messagingSenderId: '108494691697',
    projectId: 'test-app-103b4',
    storageBucket: 'test-app-103b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJw_lgot0WDcrP29iV7Qu0iVSOKe5hUqQ',
    appId: '1:108494691697:ios:1f0c72a2fb63950fb7aad0',
    messagingSenderId: '108494691697',
    projectId: 'test-app-103b4',
    storageBucket: 'test-app-103b4.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJw_lgot0WDcrP29iV7Qu0iVSOKe5hUqQ',
    appId: '1:108494691697:ios:1f0c72a2fb63950fb7aad0',
    messagingSenderId: '108494691697',
    projectId: 'test-app-103b4',
    storageBucket: 'test-app-103b4.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsF54gj1MUn8Xw5lULj9QnPup3I7p8bIE',
    appId: '1:108494691697:web:79a21c50320cdfd3b7aad0',
    messagingSenderId: '108494691697',
    projectId: 'test-app-103b4',
    authDomain: 'test-app-103b4.firebaseapp.com',
    storageBucket: 'test-app-103b4.firebasestorage.app',
    measurementId: 'G-QK93W421CP',
  );

}